name: Sync to S3

on:
  push: 
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    environment: "AWS"

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
    
    - name: Sync to S3
      run: |
        aws s3 sync $GITHUB_WORKSPACE s3://${{ secrets.AWS_S3_BUCKET_NAME }} \
          --exclude ".git/*" \
          --exclude ".github/*" \
          --exclude ".vscode/*"

      
